version: "3.7"
services:
  microproyectos-pruebas:
    container_name: microproyectos-pruebas
    image: microproyectos-pruebas:latest
    build:
      context: .
    ports:
      - "6001"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=6001
    networks:
      - ase-acad
    
  balanceador_proyectos:
    container_name: balanceador_proyectos
    image: balanceador_proyectos:latest
    build:
      context: ./balanceador
    ports:
      - "8082:80"
    networks:
      - ase-acad
networks:
  ase-acad:
